#' Plot first order neighborhood network based on package 'visNetwork'
#'
#' Positive edges are displayed in blue, negative edges in red. The color
#' depth represents the association strength.
#'
#' @param adj adjacency matrix (generated by get_adj_mat())
#' @param x target node for first order neighborhood
#' @param plot_style "circle" (default), "igraph" or "visNetwork" (useful only for few features)
#' @param node_color vector of node color(s) (default is rainbow() color set)
#' @param node_shape vector of shapes for nodes (e.g., "dot" (default), "rectangle", "triangle",
#' "hexagon", "diamond", "ellipse", "star")
#'
#' @export
#'
plot_net_selection <- function(adj, x, plot_style, node_color, node_shape){

  diag(adj) <- 0
  if (missing(plot_style)) {plot_style <- "circle"}
  if (missing(node_color)) {node_color <- rainbow(ncol(adj))}
  if (missing(node_shape)) {node_shape <- rep("dot", ncol(adj))}

  if(!x %in% colnames(adj)){
    message("Selected node was not found in adj!")
    stop()
  }

  lookup_ID <- match(x, colnames(adj))

  adj_sub <- adj[, lookup_ID, drop = FALSE]
  dim(adj_sub)

  remain_list <- list()
  for (i in 1:ncol(adj_sub)){
    # i = 1
    remain_list[[i]] <- which(sapply(adj_sub[, i], function(y) y != 0))
  }
  remain_list <- c(unlist(remain_list), lookup_ID)
  remain_list <- remain_list[!duplicated(remain_list)]

  adj_sub <- adj[remain_list, remain_list]


  qgraph_obj <- qgraph::qgraph(adj, layout = "spring", color = node_color,
                               shape = node_shape, arrows = FALSE, DoNotPlot = T, edge.labels = F,
                               borders = F, palette = "colorblind", legend = F, labels = colnames(adj),
                               label.cex = 1.5, cut = 0, esize = 1, edge.width = 1,
                               vsize = 4, bg = FALSE)

  edges <- as.data.frame(qgraph_obj$Edgelist)
  nodes <- as.data.frame(cbind(colnames(adj), colnames(adj)))
  colnames(nodes) <- c("id", "label")
  nodes$id <- rownames(nodes)
  nodes$color <- node_color

  edges$fromNode <- unlist(nodes$label)[edges$from]
  edges$toNode <- unlist(nodes$label)[edges$to]

  node_selection <- colnames(adj_sub)
  keep <- edges$fromNode %in% node_selection | edges$toNode %in% node_selection
  edges <- edges[keep, ]
  colnames(edges)[colnames(edges) == "weight"] <- "label"
  edges$title <- edges$label
  edges$id <- as.integer(rownames(edges))

  keep2 <- c(edges$from, edges$to)[!duplicated(c(edges$from, edges$to))]
  nodes <- nodes[keep2, , drop = F]

  nodes <- nodes[order(as.integer(nodes$id)), ]

  ### plotting code
  add_col_vec <- function(x) {
    x_neg <- sum(x$title < 0)
    x_pos <- sum(x$title > 0)
    edge_colors_vec <- c(colorRampPalette(c("#700007", "#ffcccc"))(x_neg),
                         colorRampPalette(c("#b3d9ff", "#001370"))(x_pos))
    x <- x[order(x$title), ]
    x$color <- edge_colors_vec
    x <- x[order(x$id), ]
    return(x)
  }
  edges <- add_col_vec(edges)
  plot_style0 = plot_style

  nodes_edges <- list(nodes = nodes, edges = edges)
  net <- visNetwork::visNetwork(nodes_edges$nodes, nodes_edges$edges)
  net <- visNetwork::visOptions(net, highlightNearest = TRUE,
                                nodesIdSelection = TRUE)
  net <- visNetwork::visEdges(net, smooth = F, width = 3)
  net <- visNetwork::visNodes(net, size = 20, font = list(size = 25,
                                                          multi = "html"), shadow = list(enabled = TRUE))
  net <- visNetwork::visPhysics(net, stabilization = T)
  if (plot_style0 == "igraph") {
    net <- visNetwork::visIgraphLayout(net, layout = "layout_nicely",
                                       physics = FALSE)
  } else if (plot_style0 == "circle") {
    net <- visNetwork::visIgraphLayout(net, layout = "layout_in_circle",
                                       physics = FALSE)
  } else if (plot_style0 == "visNetwork") {
    net <- net
  }

  net$x$nodes[match(lookup_ID, net$x$nodes$id), "x"] <- 0
  net$x$nodes[match(lookup_ID, net$x$nodes$id), "y"] <- 0

  return(net)

}
