#' Internal function
#'
#' @param B_Rho_Phi_alphap_alphaq ...
#' @param X ...
#' @param Y ...
#' @param Y_levels ...
#' @param p ...
#' @param q ...
#' @param groups_X ...
#' @param prior_X ...
#' @param use_prior ...
#'
grad_neglogli_plain <- function(B_Rho_Phi_alphap_alphaq, X, Y, Y_levels, p, q, groups_X, prior_X, use_prior){
  x2 <- Inv_B_Rho_Phi_alphap_alphaq(B_Rho_Phi_alphap_alphaq, p, q)
  x1 <- grad_neglogli_R(x2, X, Y, Y_levels, groups_X, prior_X, use_prior)
  # if (grad == "C"){
  #   x1 <- grad_neglogli_C(x2, X, Y, Y_levels)
  # } else if (grad == "Py") {
  #   x1 <- grad_neglogli_Py(x2, X, Y, Y_levels, groups_X, prior_X, use_prior)
  # } else if (grad == "R") {
  #   x1 <- grad_neglogli_R(x2, X, Y, Y_levels, groups_X, prior_X, use_prior)
  # }
  # print(x1[[1]])
  return(x1)
}
