#' Internal function
#'
#' @param x ...
#' @param X ...
#' @param Y ...
#' @param Y_levels ...
#' @param p ...
#' @param q ...
#' @param groups_X ...
#' @param prior_X ...
#' @param use_prior ...
#'
grad_f_temp <- function(x, X, Y, Y_levels, p, q, groups_X, prior_X, use_prior){
  x2 <- grad_neglogli_plain(x, X, Y, Y_levels, p, q, groups_X, prior_X, use_prior)
  x3 <- B_Rho_Phi_alphap_alphaq(x2)
  return(x3)
}
