#' Plot network based on package 'visNetwork'
#'
#' Positive edges are displayed in blue, negative edges in red. The color
#' depth represents the association strength.
#'
#' @param x adjacency matrix (generated by get_adj_mat())
#' @param plot_style "circle", "igraph" or "visNetwork" (useful only for few features)
#' @param node_color vector of colors for nodes (default is rainbow() color set)
#' @param node_shape vector of shapes for nodes (e.g., "dot", "rectangle", "triangle",
#' "hexagon", "diamond", "ellipse", "star")
#' @param node_scale logical, If TRUE, node sizes are proportional to feature 
#' impact (default = FALSE)
#' @param node_bold logical, If TRUE, node titles are displayed as bold font 
#' (default = FALSE)
#'
#'
#' @export
#' 
plot_net <- function (x, plot_style, node_color, node_shape, node_scale, node_bold) 
{
  
  diag(x) <- 0
  if (ncol(x) * nrow(x) > 250000) {
    message("Due to the high number of features, plotting may take a while or errors occur!")
  }
  if (missing(plot_style)) {
    plot_style <- "igraph"
  }
  if (missing(node_color)) {
    node_color <- rainbow(ncol(x))
  }
  if (missing(node_shape)) {
    node_shape <- rep("dot", ncol(x))
  }
  if (missing(node_scale)) {
    node_scale <- FALSE
  }
  if (missing(node_bold)) {
    node_bold <- FALSE
  }
  
  qgraph_obj <- qgraph::qgraph(x, layout = "spring", color = node_color, 
                               shape = node_shape, arrows = FALSE, DoNotPlot = T, edge.labels = F, 
                               borders = F, palette = "colorblind", legend = F, labels = colnames(x), 
                               label.cex = 1.5, cut = 0, esize = 1, edge.width = 1, 
                               vsize = 4, bg = FALSE)
  
  nodes <- as.data.frame(as.character(1:nrow(x)))
  names(nodes) <- "id"
  node_bold
  if(node_bold){
    nodes$label <- paste0("<b>", colnames(x))
  } else {
    nodes$label <- colnames(x)
  }
  nodes$color <- node_color
  nodes$shape <- node_shape
  
  
  edges <- qgraph_obj$Edgelist
  edges <- as.data.frame(cbind(edges$from, edges$to, edges$weight))
  names(edges) <- c("from", "to", "title")
  edges$id <- 1:nrow(edges)
  add_col_vec <- function(x) {
    x_neg <- sum(x$title < 0)
    x_pos <- sum(x$title > 0)
    edge_colors_vec <- c(colorRampPalette(c("#700007", "#ffcccc"))(x_neg), 
                         colorRampPalette(c("#b3d9ff", "#001370"))(x_pos))
    x <- x[order(x$title), ]
    x$color <- edge_colors_vec
    x <- x[order(x$id), ]
    return(x)
  }
  edges <- add_col_vec(edges)
  plot_style0 = plot_style
  ## add node scaling option
  if(node_scale){
    feature_impact <- (abs(colSums(x))+1)*10
    nodes$value <- feature_impact
    nodes_edges <- list(nodes = nodes, edges = edges)
    net <- visNetwork::visNetwork(nodes_edges$nodes, nodes_edges$edges, width = "100%", height = 1200)
    net <- visNetwork::visNodes(net, scaling = list(min = 10, max = 40))
  }
  
  nodes_edges <- list(nodes = nodes, edges = edges)
  net <- visNetwork::visNetwork(nodes_edges$nodes, nodes_edges$edges)
  net <- visNetwork::visOptions(net, highlightNearest = TRUE,
                                nodesIdSelection = TRUE)
  net <- visNetwork::visEdges(net, smooth = F)
  net <- visNetwork::visNodes(net,
                              size = 20,
                              font = list("size" = 25,
                                          "multi" = "html"),
                              shadow = list("enabled" = TRUE)
  )
  
  
  net <- visNetwork::visPhysics(net, stabilization = T)
  if (plot_style0 == "igraph") {
    net <- visNetwork::visIgraphLayout(net, layout = "layout_nicely", 
                                       physics = FALSE)
  }
  else if (plot_style0 == "circle") {
    net <- visNetwork::visIgraphLayout(net, layout = "layout_in_circle", 
                                       physics = FALSE)
  }
  else if (plot_style0 == "visNetwork") {
    net <- net
  }
  
  return(net)
}